name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install flake8
      - run: flake8 . --count --select=E9 --show-source --statistics
